<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="logistic">

    <!-- Incluide SHARK xacro -->
    <xacro:include filename="$(find shark_description)/urdf/shark.xacro" />
    
    <!-- Include Velodyne xacro -->
    <xacro:include filename="$(find sensors_description)/urdf/velodyne.xacro" />

    <property name="base_len" value="${base_len}" />
    <property name="base_height" value="${base_height}" />

    <!-- Define Velodyne macro -->
    <xacro:VLP-16 parent="base_link" name="velodyne" min_angle="-3.1415926535897931" max_angle="0.0">
        <origin xyz="${base_len/2 - 0.07} 0 ${base_height/2}" rpy="0 0 0" />
    </xacro:VLP-16>

</robot>
