<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="logistic">

    <!-- Incluide SHARK xacro -->
    <xacro:include filename="$(find shark_description)/urdf/shark.xacro" />
    
    <!-- Include Velodyne xacro -->
    <xacro:include filename="$(find sensors_description)/urdf/velodyne.xacro" />

    <property name="base_len" value="${base_len}" />
    <property name="base_height" value="${base_height}" />

    <!-- Define Velodyne macro -->
    <xacro:VLP-16 parent="base_link" name="velodyne">
        <origin xyz="${base_len/2 - 0.07} 0 ${base_height/2}" rpy="0 0 0" />
    </xacro:VLP-16>

    <xacro:include filename="$(find sensors_description)/urdf/hokuyo.xacro" />

    <xacro:sensor_hokuyo parent="base_link" xyz="${base_len/2 + 0.017 + 0.024} 0 ${0.02 - base_height/2}" rpy="3.14 0 0" name="ground"/>

    <xacro:macro name="imu" params="parent xyz rpy">
    <link name="imu_link"/>
    <joint name="imu_joint" type="fixed">
      <parent link="${parent}"/>
      <child link="imu_link"/>
      <origin xyz="${xyz}" rpy="${rpy}"/>
    </joint>
    </xacro:macro>

    <xacro:imu parent="base_link" xyz="${base_len/2 + 0.0625} 0 ${0.02 - base_height/2}" rpy="0 0 0"/>

</robot>
